# Use postgres/example user/password credentials
version: '3.9'

services:
  postrgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postrges
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.ru
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
    ports:
      - 8080:80

volumes:
  postgres_data: